print("Welcome to CleanRepo!")
print("")
print("                         .       .")
print("                        / `.   .' \\")
print("                .---.  <    > <    >  .---.")
print("                |    \\  \\ - ~ ~ - /  /    |")
print("                 ~-..-~             ~-..-~")
print("             \\~~~\\.'                    `./~~~/")
print("   .-~~^-.    \\__/                        \\__/")
print(" .'  O    \\     /               /       \\  \\")
print("(_____,    `._.'               |         }  \\/~~~/")
print(" `----.          /       }     |        /    \\__/")
print("       `-.      |       /      |       /      `. ,~~|")
print("           ~-.__|      /_ - ~ ^|      /- _      `..-'")
print("                |     /        |     /     ~-.     `-. _||_||_")
print("                |_____|        |_____|         ~ - . _ _ _ _ _>")
print("")
print("✅ Clean repo — no hidden surprises here!")